/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlAnalyzerRouteImport } from './routes/url-analyzer'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as HeadersRouteImport } from './routes/headers'
import { Route as IndexRouteImport } from './routes/index'

const UrlAnalyzerRoute = UrlAnalyzerRouteImport.update({
  id: '/url-analyzer',
  path: '/url-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadersRoute = HeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/headers': typeof HeadersRoute
  '/password': typeof PasswordRoute
  '/url-analyzer': typeof UrlAnalyzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/headers': typeof HeadersRoute
  '/password': typeof PasswordRoute
  '/url-analyzer': typeof UrlAnalyzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/headers': typeof HeadersRoute
  '/password': typeof PasswordRoute
  '/url-analyzer': typeof UrlAnalyzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/headers' | '/password' | '/url-analyzer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/headers' | '/password' | '/url-analyzer'
  id: '__root__' | '/' | '/headers' | '/password' | '/url-analyzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeadersRoute: typeof HeadersRoute
  PasswordRoute: typeof PasswordRoute
  UrlAnalyzerRoute: typeof UrlAnalyzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url-analyzer': {
      id: '/url-analyzer'
      path: '/url-analyzer'
      fullPath: '/url-analyzer'
      preLoaderRoute: typeof UrlAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headers': {
      id: '/headers'
      path: '/headers'
      fullPath: '/headers'
      preLoaderRoute: typeof HeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeadersRoute: HeadersRoute,
  PasswordRoute: PasswordRoute,
  UrlAnalyzerRoute: UrlAnalyzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
